### ISSUE TITLE
Foursquare not working 

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/prox-server#72]
From the server logs.
```
Dec 02 15:24:27 ip-172-31-12-95 python[18051]: ERROR:prox:Exeption hitting foursquare
Dec 02 15:24:27 ip-172-31-12-95 python[18051]: Traceback (most recent call last):
Dec 02 15:24:27 ip-172-31-12-95 python[18051]:   File "app/search.py", line 89, in getVenueDetailsFromProvider
Dec 02 15:24:27 ip-172-31-12-95 python[18051]:     info = resolve(idObj)
Dec 02 15:24:27 ip-172-31-12-95 python[18051]:   File "app/providers/fs.py", line 7, in resolve
Dec 02 15:24:27 ip-172-31-12-95 python[18051]:     fsId = idObj["namespace_id"]
Dec 02 15:24:27 ip-172-31-12-95 python[18051]: KeyError: 'namespace_id'
```

**Comment by liuche** [comment]
Looks like it could because the fs code is using the Factual namespace_id, rather than fetching from the regex slug like Yelp.
