### ISSUE TITLE
Error while update_gcals on production

### ISSUE THREAD

**Issue by jhugman** [mozilla-mobile/prox-server#74]
```
Dec 02 16:52:27 ip-172-31-12-95 systemd[1]: Started prox update gcals.
Dec 02 16:52:34 ip-172-31-12-95 python[25314]: ERROR:prox:Error running scheduled calendar fetch
Dec 02 16:52:34 ip-172-31-12-95 python[25314]: Traceback (most recent call last):
Dec 02 16:52:34 ip-172-31-12-95 python[25314]:   File "/home/prox/prox-server/app/request_handler.py", line 264, in updateFromGcals
Dec 02 16:52:34 ip-172-31-12-95 python[25314]:     loadCalendarEvents(datetime.timedelta(days=1))
Dec 02 16:52:34 ip-172-31-12-95 python[25314]:   File "/home/prox/prox-server/app/request_handler.py", line 281, in loadCalendarEvents
Dec 02 16:52:34 ip-172-31-12-95 python[25314]:     writeEventRecord(eventObj)
Dec 02 16:52:34 ip-172-31-12-95 python[25314]:   File "/home/prox/prox-server/app/request_handler.py", line 222, in writeEventRecord
Dec 02 16:52:34 ip-172-31-12-95 python[25314]:     "locations/" + key: geo
Dec 02 16:52:34 ip-172-31-12-95 python[25314]:   File "/home/prox/prox-server/env/local/lib/python2.7/site-packages/pyrebase/pyrebase.py", line 308, in update
Dec 02 16:52:34 ip-172-31-12-95 python[25314]:     raise_detailed_error(request_object)
Dec 02 16:52:34 ip-172-31-12-95 python[25314]:   File "/home/prox/prox-server/env/local/lib/python2.7/site-packages/pyrebase/pyrebase.py", line 446, in raise_detailed_error
Dec 02 16:52:34 ip-172-31-12-95 python[25314]:     raise HTTPError(e, request_object.text)
Dec 02 16:52:34 ip-172-31-12-95 python[25314]: HTTPError: [Errno 400 Client Error: Bad Request for url: https://prox-server-cf63e.firebaseio.com/production/events.json] {
Dec 02 16:52:34 ip-172-31-12-95 python[25314]:   "error" : "Invalid data; couldn't parse JSON object. Are you sending a JSON object with valid key names?"
Dec 02 16:52:34 ip-172-31-12-95 python[25314]: }
```

**Comment by liuche** [comment]
The first part of this (literally fixing this firebase key problem) is closed by #76 . The second part (removing the unnecessary scheduler and delay) is part of #77 but is not strictly necessary to land for kona.
